# Exporting Component Description of INIT_MONITOR to TCL
# Family: PolarFireSoC
# Part Number: MPFS250T_ES-FCVG484E
# Create and Configure the core component INIT_MONITOR
create_and_configure_core -core_vlnv {Microsemi:SgCore:PFSOC_INIT_MONITOR:*} -component_name {INIT_MONITOR} -params {\
"BANK_0_CALIB_STATUS_ENABLED:false"  \
"BANK_0_CALIB_STATUS_SIMULATION_DELAY:1"  \
"BANK_0_RECALIBRATION_ENABLED:false"  \
"BANK_0_VDDI_STATUS_ENABLED:false"  \
"BANK_0_VDDI_STATUS_SIMULATION_DELAY:1"  \
"BANK_1_CALIB_STATUS_ENABLED:false"  \
"BANK_1_CALIB_STATUS_SIMULATION_DELAY:1"  \
"BANK_1_RECALIBRATION_ENABLED:false"  \
"BANK_1_VDDI_STATUS_ENABLED:false"  \
"BANK_1_VDDI_STATUS_SIMULATION_DELAY:1"  \
"BANK_7_CALIB_STATUS_ENABLED:true"  \
"BANK_7_CALIB_STATUS_SIMULATION_DELAY:1"  \
"BANK_7_RECALIBRATION_ENABLED:false"  \
"BANK_7_VDDI_STATUS_ENABLED:false"  \
"BANK_7_VDDI_STATUS_SIMULATION_DELAY:1"  \
"BANK_8_CALIB_STATUS_ENABLED:true"  \
"BANK_8_CALIB_STATUS_SIMULATION_DELAY:1"  \
"BANK_8_RECALIBRATION_ENABLED:false"  \
"BANK_8_VDDI_STATUS_ENABLED:false"  \
"BANK_8_VDDI_STATUS_SIMULATION_DELAY:1"  \
"BANK_9_CALIB_STATUS_ENABLED:true"  \
"BANK_9_CALIB_STATUS_SIMULATION_DELAY:1"  \
"BANK_9_RECALIBRATION_ENABLED:false"  \
"BANK_9_VDDI_STATUS_ENABLED:false"  \
"BANK_9_VDDI_STATUS_SIMULATION_DELAY:1"  \
"DEVICE_INIT_DONE_SIMULATION_DELAY:7"  \
"FABRIC_POR_N_SIMULATION_DELAY:1"  \
"LATCH_SC_OUTPUTS:false"  \
"PCIE_INIT_DONE_SIMULATION_DELAY:4"  \
"SHOW_BANK_0_CALIB_STATUS_ENABLED:false"  \
"SHOW_BANK_0_RECALIBRATION_ENABLED:true"  \
"SHOW_BANK_0_VDDI_STATUS_ENABLED:true"  \
"SHOW_BANK_1_CALIB_STATUS_ENABLED:false"  \
"SHOW_BANK_1_RECALIBRATION_ENABLED:true"  \
"SHOW_BANK_1_VDDI_STATUS_ENABLED:true"  \
"SHOW_BANK_7_CALIB_STATUS_ENABLED:false"  \
"SHOW_BANK_7_RECALIBRATION_ENABLED:false"  \
"SHOW_BANK_7_VDDI_STATUS_ENABLED:false"  \
"SHOW_BANK_8_CALIB_STATUS_ENABLED:false"  \
"SHOW_BANK_8_RECALIBRATION_ENABLED:0"  \
"SHOW_BANK_8_VDDI_STATUS_ENABLED:false"  \
"SHOW_BANK_9_CALIB_STATUS_ENABLED:false"  \
"SHOW_BANK_9_RECALIBRATION_ENABLED:false"  \
"SHOW_BANK_9_VDDI_STATUS_ENABLED:false"  \
"SRAM_INIT_DONE_SIMULATION_DELAY:6"  \
"USRAM_INIT_DONE_SIMULATION_DELAY:5"   }
# Exporting Component Description of INIT_MONITOR to TCL done
