########## This file is automatically generated. Any changes to this file will be lost. ##########
########## If you have your own constraints tcl file, please add it to the project ##########
########## by using the "Set custom config file" constraint in the HLS Constraints dialog. ##########
source $env(SHLS_ROOT_DIR)/examples/shls.tcl
set_project PolarFireSoC MPFS250T Icicle_SoC

set_parameter CLOCK_PERIOD 10
