########## This file is automatically generated. Any changes to this file will be lost. ##########
########## If you have your own constraints tcl file, please add it to the project ##########
########## by using the "Set custom config file" constraint in the HLS Constraints dialog. ##########
source $env(SHLS_ROOT_DIR)/examples/legup.tcl
set_project PolarFire MPF300 MiV_SoC
set_custom_test_bench_file WideMultTopPf_Tb.sv
set_custom_test_bench_module WideMultTopPf_Tb

set_parameter USE_FIFO_FOR_PIPELINE_REG 1
