########## This file is automatically generated. Any changes to this file will be lost. ##########
########### If you have your own constraints tcl file, please add it to the project ##########
########### by using the "Set custom config file" constraint in the HLS Constraints dialog. ##########
source $env(SHLS_ROOT_DIR)/examples/shls.tcl
set_project PolarFireSoC MPFS250T Icicle_SoC

# Include a free-running counter in the HLS susbsystem for profiling purposes 
set_parameter SOC_PROFILER_COUNTER 1

# These parameters tell SmartHLS how to integrate the generated HDL 
# into a SmartDesign. In this cace: the Icicle Kit Reference design.
# This will no longer be necessary for the IcicleKit Ref design in the next 
# release of SmartHLS, but will still be avilable for custom designs.
set_parameter SOC_BD_NAME                 FIC_0_PERIPHERALS
set_parameter SOC_AXI_INITIATOR           AXI2AXI_TO_HLS:AXI4_MASTER
set_parameter SOC_AXI_TARGET              AXI2AXI_FROM_HLS:AXI4_SLAVE
set_parameter SOC_RESET                   ARESET
set_parameter SOC_CLOCK                   ACLK
# Using 256MB of FIC-0 address space range: 0x7000_0000 - 0x7040_0000 (4MB)
set_parameter SOC_FABRIC_BASE_ADDRESS     0x70000000
set_parameter SOC_FABRIC_SIZE             0x400000
# Starting from Cached memory base address (0x80000000) all the way up to just 
# before FIC-1 (~1.7GB)
set_parameter SOC_CPU_MEM_BASE_ADDRESS    0x80000000
set_parameter SOC_CPU_MEM_SIZE            0x60000000

