########## This file is automatically generated. Any changes to this file will be lost. ##########
########## If you have your own custom Makefile, please name it Makefile.user. ##########
NAME = RGB2YCbCr
LOCAL_CONFIG = -legup-config=config.tcl
SRCS = RGB2YCbCr.cpp
GUI_BASE_DIR =
LEVEL = $(SHLS_ROOT_DIR)/examples


USER_CXX_FLAG += -O3 -pg -Wall -Wno-strict-aliasing -Wno-unused-label -Wno-unknown-pragmas -Wno-attributes -I$(SHLS_ROOT_DIR)/smarthls-library

ifneq ("$(wildcard $(GUI_BASE_DIR)Makefile.user)","")
include $(GUI_BASE_DIR)Makefile.user
endif
include $(LEVEL)/Makefile.common

